routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', DashboardController::class);
Route::resource('pelanggan', PelangganController::class);
Route::resource('barang', BarangController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('pembelian', PembelianController::class);
Route::resource('penjualan', PenjualanController::class);

Auth::routes();

app/Models/Pelanggan.php
<?php

namespace App\Models;

use App\Models\Penjualan;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Pelanggan extends Model
{
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
    protected $table = 'pelanggan';

    protected $fillable = [
        'kode_pelanggan', 'nama_pelanggan', 'alamat', 'no_telepon'
    ];

    /**
     * Get the user that owns the Pelanggan
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function penjualan(): BelongsTo
    {
        return $this->belongsTo(Penjualan::class, 'id_pelanggan');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data = [
            'title' => 'Dashboard',
            'active' => 'Dashboard'
        ];

        return view('dashboard/index', $data);
    }
}

app/Http/Controllers/PelangganController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pelanggan;
use Illuminate\Http\Request;

class PelangganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title' => 'Pelanggan',
            'active' => 'Pelanggan',
            'results' => Pelanggan::get(),
            'no' => 1
        ];

        return view('dashboard.pelanggan.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Pelanggan',
            'active' => 'Pelanggan'
        ];

        return view('dashboard.pelanggan.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'kode_pelanggan' => 'required|string|max:150|min:6|unique:pelanggan,kode_pelanggan',
            'nama_pelanggan' => 'required|string|max:200|min:6',
            'alamat' => 'required|string|min:6|max:200',
            'no_telepon' => 'required|numeric'
        ]);

        $query = Pelanggan::create([
            'kode_pelanggan' => $request->kode_pelanggan,
            'nama_pelanggan' => $request->nama_pelanggan,
            'alamat' => $request->alamat,
            'no_telepon' => $request->no_telepon
        ]);

        if ($query) {
            return redirect()->route('pelanggan.index')->with("success", "Data Baru Berhasil Ditambahkan");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Ditambahkan)");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pelanggan  $pelanggan
     * @return \Illuminate\Http\Response
     */
    public function show(Pelanggan $pelanggan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pelanggan  $pelanggan
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => 'Pelanggan',
            'active' => 'Pelanggan',
            'result' => Pelanggan::findOrFail($id)
        ];

        return view('dashboard.pelanggan.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pelanggan  $pelanggan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'kode_pelanggan' => 'required|string|max:150|min:6',
            'nama_pelanggan' => 'required|string|max:200|min:6',
            'alamat' => 'required|string|min:6|max:200',
            'no_telepon' => 'required|numeric'
        ]);

        $query = Pelanggan::findOrFail($id);

        $query->update([
            'kode_pelanggan' => $request->kode_pelanggan,
            'nama_pelanggan' => $request->nama_pelanggan,
            'alamat' => $request->alamat,
            'no_telepon' => $request->no_telepon
        ]);

        if ($query) {
            return redirect()->route('pelanggan.index')->with("success", "Data Baru Berhasil Diperbaharui");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Diperbaharui)");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pelanggan  $pelanggan
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = Pelanggan::findOrFail($id);
        $query->delete();

        if ($query) {
            return redirect()->route('pelanggan.index')->with("success", "Data Baru Berhasil Dihapuskan");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Dihapuskan)");
        }
    }
}

resources/views/dashboard/pelanggan/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="container">
            <div class="card border-success">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                    Tambah Data Pelanggan
                    <a href="{{ route('pelanggan.index') }}" class="btn btn-outline-success btn-sm">Kembali</a>
                </div>
                <div class="card-body ">
                    <form action="{{ route('pelanggan.store') }}" method="post">
                        @csrf
                        <div class="mb-3 row">
                            <label for="kode_pelanggan" class="col-sm-2 col-form-label">Kode Pelanggan</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('kode_pelanggan') is-invalid @enderror"
                                    name="kode_pelanggan" id="kode_pelanggan" autocomplete="off"
                                    value="{{ old('kode_pelanggan') }}">
                                @error('kode_pelanggan')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nama_pelanggan" class="col-sm-2 col-form-label">Nama Pelanggan</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('nama_pelanggan') is-invalid @enderror"
                                    name="nama_pelanggan" id="nama_pelanggan" autocomplete="off"
                                    value="{{ old('nama_pelanggan') }}">
                                @error('nama_pelanggan')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('alamat') is-invalid @enderror"
                                    name="alamat" id="alamat" autocomplete="off" value="{{ old('alamat') }}">
                                @error('alamat')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="no_telepon" class="col-sm-2 col-form-label">No Telepon</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('no_telepon') is-invalid @enderror"
                                    name="no_telepon" id="no_telepon" autocomplete="off" value="{{ old('no_telepon') }}">
                                @error('no_telepon')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pelanggan/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="container">
            <div class="card border-success">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                    Edit Data Pelanggan
                    <a href="{{ route('pelanggan.index') }}" class="btn btn-outline-success btn-sm">Kembali</a>
                </div>
                <div class="card-body ">
                    <form action="{{ route('pelanggan.update', $result->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="mb-3 row">
                            <label for="kode_pelanggan" class="col-sm-2 col-form-label">Kode Pelanggan</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('kode_pelanggan') is-invalid @enderror"
                                    name="kode_pelanggan" id="kode_pelanggan" autocomplete="off"
                                    value="{{ $result->kode_pelanggan }}">
                                @error('kode_pelanggan')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nama_pelanggan" class="col-sm-2 col-form-label">Nama Pelanggan</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('nama_pelanggan') is-invalid @enderror"
                                    name="nama_pelanggan" id="nama_pelanggan" autocomplete="off"
                                    value="{{ $result->nama_pelanggan }}">
                                @error('nama_pelanggan')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="alamat" class="col-sm-2 col-form-label">Alamat</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('alamat') is-invalid @enderror"
                                    name="alamat" id="alamat" autocomplete="off" value="{{ $result->alamat }}">
                                @error('alamat')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="no_telepon" class="col-sm-2 col-form-label">No Telepon</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('no_telepon') is-invalid @enderror"
                                    name="no_telepon" id="no_telepon" autocomplete="off" value="{{ $result->no_telepon }}">
                                @error('no_telepon')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-warning btn-sm" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pelanggan/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="card border-success">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                Form Pelanggan
                <a href="{{ route('pelanggan.create') }}" class="btn btn-outline-primary btn-sm">Tambah Data</a>
            </div>
            <div class="card-body table-responsive">
                <table id="example" class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Kode Pelanggan</th>
                            <th>Nama Pelanggan</th>
                            <th>alamat</th>
                            <th>No Telepon</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($results as $res)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $res->kode_pelanggan }}</td>
                                <td>{{ $res->nama_pelanggan }}</td>
                                <td>{{ $res->alamat }}</td>
                                <td>{{ $res->no_telepon }}</td>
                                <td>
                                    <form onsubmit="return confirm('Apakah anda yakin?')"
                                        action="{{ route('pelanggan.destroy', $res->id) }}" method="POST">
                                        <a href="{{ route('pelanggan.edit', $res->id) }}"
                                            class="btn btn-outline-warning btn-sm btn-block">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="btn btn-outline-danger btn-sm btn-block">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection