routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', DashboardController::class);
Route::resource('pelanggan', PelangganController::class);
Route::resource('barang', BarangController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('pembelian', PembelianController::class);
Route::resource('penjualan', PenjualanController::class);

Auth::routes();

app/Models/Penjualan.php
<?php

namespace App\Models;

use App\Models\Pelanggan;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\belongsToMany;

class Penjualan extends Model
{
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
    protected $table = 'penjualan';

    protected $fillable = [
        'no_penjualan', 'tanggal', 'id_pelanggan', 'id_barang', 'jumlah_barang', 'harga_barang', 'created_at', 'created_by'
    ];

    /**
     * Get the user associated with the Penjualan
     *
     * @return hasMany
     */
    public function pelanggan(): hasMany
    {
        return $this->hasMany(Pelanggan::class, 'id');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data = [
            'title' => 'Dashboard',
            'active' => 'Dashboard'
        ];

        return view('dashboard/index', $data);
    }
}

app/Http/Controllers/PenjualanController.php
<?php

namespace App\Http\Controllers;

use DateTime;
use App\Models\Barang;
use App\Models\Pelanggan;
use App\Models\Penjualan;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class PenjualanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title' => 'Penjualan',
            'active' => 'Penjualan',
            'results' => DB::table('penjualan')
                ->join('pelanggan', 'penjualan.id_pelanggan', '=', 'pelanggan.id')
                ->join('barang', 'penjualan.id_barang', '=', 'barang.id')
                ->join('users', 'penjualan.created_by', '=', 'users.id')
                ->select('penjualan.*', 'pelanggan.nama_pelanggan', 'barang.nama_barang', 'users.name')
                ->get(),
            'no' => 1
        ];

        return view('dashboard.penjualan.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Penjualan',
            'active' => 'Penjualan',
            'results' => Penjualan::get(),
            'pelanggans' => Pelanggan::get(),
            'barangs' => Barang::get()
        ];

        return view('dashboard.penjualan.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'no_penjualan' => 'required|string|max:150|min:6|unique:penjualan,no_penjualan',
            'tanggal' => 'required',
            'id_pelanggan' => 'required',
            'id_barang' => 'required',
            'jumlah' => 'required',
            'harga' => 'required'
        ]);

        $cekStok = Barang::findOrFail($request->id_barang);

        if ($request->jumlah > $cekStok->stok_barang) {
            return redirect()->route('penjualan.index')->with("error", "Jumlah Stock Terlalu Sedikit");
        }

        $query = Penjualan::create([
            'no_penjualan' => $request->no_penjualan,
            'tanggal' => $request->tanggal,
            'id_pelanggan' => $request->id_pelanggan,
            'id_barang' => $request->id_barang,
            'jumlah_barang' => $request->jumlah,
            'harga_barang' => $request->harga,
            'created_at' => new DateTime(),
            'created_by' => Auth::user()->id
        ]);

        if ($query) {
            return redirect()->route('penjualan.index')->with("success", "Data Baru Berhasil Ditambahkan");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Ditambahkan");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Penjualan  $penjualan
     * @return \Illuminate\Http\Response
     */
    public function show(Penjualan $penjualan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Penjualan  $penjualan
     * @return \Illuminate\Http\Response
     */
    public function edit(Penjualan $penjualan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Penjualan  $penjualan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Penjualan $penjualan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Penjualan  $penjualan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Penjualan $penjualan)
    {
        //
    }
}

resources/views/dashboard/penjualan/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="container">
            <div class="card border-success">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                    Tambah Data Penjualan
                    <a href="{{ route('penjualan.index') }}" class="btn btn-outline-success btn-sm">Kembali</a>
                </div>
                <div class="card-body ">
                    <form action="{{ route('penjualan.store') }}" method="post">
                        @csrf
                        <div class="mb-3 row">
                            <label for="no_penjualan" class="col-sm-2 col-form-label">No penjualan</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('no_penjualan') is-invalid @enderror"
                                    name="no_penjualan" id="no_penjualan" autocomplete="off"
                                    value="{{ old('no_penjualan') }}">
                                @error('no_penjualan')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="tanggal" class="col-sm-2 col-form-label">Tanggal</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control @error('tanggal') is-invalid @enderror"
                                    name="tanggal" id="tanggal" autocomplete="off" value="{{ old('tanggal') }}">
                                @error('tanggal')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="pelanggan" class="col-sm-2 col-form-label">Pelanggan</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="id_pelanggan" required>
                                    <option value="">--- Pilih Pelanggan ---</option>
                                    @foreach ($pelanggans as $res)
                                        <option value="{{ $res->id }}">{{ $res->nama_pelanggan }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="barang" class="col-sm-2 col-form-label">Barang</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="id_barang" required>
                                    <option value="">--- Pilih Barang ---</option>
                                    @foreach ($barangs as $res)
                                        <option value="{{ $res->id }}">{{ $res->nama_barang }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="jumlah" class="col-sm-2 col-form-label">Jumlah</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('jumlah') is-invalid @enderror"
                                    name="jumlah" id="jumlah" autocomplete="off" value="{{ old('jumlah') }}">
                                @error('jumlah')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('harga') is-invalid @enderror"
                                    name="harga" id="harga" autocomplete="off" value="{{ old('harga') }}">
                                @error('harga')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/penjualan/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="card border-success">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                Form Penjualan
                <a href="{{ route('penjualan.create') }}" class="btn btn-outline-primary btn-sm">Tambah Data</a>
            </div>
            <div class="card-body table-responsive">
                <table id="example" class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>No Penjualan</th>
                            <th>Tanggal</th>
                            <th>Pelanggan</th>
                            <th>Barang</th>
                            <th>Jumlah</th>
                            <th>Harga</th>
                            <th>Created At</th>
                            <th>Created By</th>
                            {{-- <th>Aksi</th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($results as $res)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $res->no_penjualan }}</td>
                                <td>{{ $res->tanggal }}</td>
                                <td>{{ $res->nama_pelanggan }}</td>
                                <td>{{ $res->nama_barang }}</td>
                                <td>{{ $res->jumlah_barang }}</td>
                                <td>{{ $res->harga_barang }}</td>
                                <td>{{ $res->created_at }}</td>
                                <td>{{ $res->name ?? 'No Data' }}</td>
                                {{-- <td>
                                    <form onsubmit="return confirm('Apakah anda yakin?')"
                                        action="{{ route('penjualan.destroy', $res->id) }}" method="POST">
                                        <a href="{{ route('penjualan.edit', $res->id) }}"
                                            class="btn btn-outline-warning btn-sm btn-block">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="btn btn-outline-danger btn-sm btn-block">Hapus</button>
                                    </form>
                                </td> --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection