routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', DashboardController::class);
Route::resource('pelanggan', PelangganController::class);
Route::resource('barang', BarangController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('pembelian', PembelianController::class);
Route::resource('penjualan', PenjualanController::class);

Auth::routes();

app/Models/Barang.php
<?php

namespace App\Models;

use App\Models\Pembelian;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Barang extends Model
{
    use HasFactory;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;
    protected $table = 'barang';

    protected $fillable = [
        'kode_barang', 'nama_barang', 'stok_barang', 'harga_barang'
    ];

    public function pembelian(): BelongsTo
    {
        return $this->belongsTo(Pembelian::class, 'id_barang');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use Illuminate\Http\Request;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'title' => 'Barang',
            'active' => 'Barang',
            'results' => Barang::get(),
            'no' => 1
        ];

        return view('dashboard.barang.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'title' => 'Barang',
            'active' => 'Barang'
        ];

        return view('dashboard.barang.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'kode_barang' => 'required|string|max:150|min:6|unique:barang,kode_barang',
            'nama_barang' => 'required|string|max:200|min:6',
            'stok' => 'required|numeric',
            'harga' => 'required|numeric'
        ]);

        $query = Barang::create([
            'kode_barang' => $request->kode_barang,
            'nama_barang' => $request->nama_barang,
            'stok_barang' => $request->stok,
            'harga_barang' => $request->harga
        ]);

        if ($query) {
            return redirect()->route('barang.index')->with("success", "Data Baru Berhasil Ditambahkan");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Ditambahkan)");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function show(Barang $barang)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'title' => 'Barang',
            'active' => 'Barang',
            'result' => Barang::findOrFail($id)
        ];

        return view('dashboard.barang.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'kode_barang' => 'required|string|max:150|min:6',
            'nama_barang' => 'required|string|max:200|min:6',
            'stok' => 'required|numeric',
            'harga' => 'required|numeric'
        ]);

        $query = Barang::findOrFail($id);

        $query->update([
            'kode_barang' => $request->kode_barang,
            'nama_barang' => $request->nama_barang,
            'stok_barang' => $request->stok,
            'harga_barang' => $request->harga
        ]);

        if ($query) {
            return redirect()->route('barang.index')->with("success", "Data Baru Berhasil Diperbaharui");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Diperbaharui)");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Barang  $barang
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = Barang::findOrFail($id);
        $query->delete();

        if ($query) {
            return redirect()->route('barang.index')->with("success", "Data Baru Berhasil Dihapuskan");
        } else {
            return redirect()->back()->withInput()->with("error", "Data Baru Gagal Dihapuskan)");
        }
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $data = [
            'title' => 'Dashboard',
            'active' => 'Dashboard'
        ];

        return view('dashboard/index', $data);
    }
}

resources/views/dashboard/barang/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="container">
            <div class="card border-success">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                    Tambah Data Barang
                    <a href="{{ route('barang.index') }}" class="btn btn-outline-success btn-sm">Kembali</a>
                </div>
                <div class="card-body ">
                    <form action="{{ route('barang.store') }}" method="post">
                        @csrf
                        <div class="mb-3 row">
                            <label for="kode_barang" class="col-sm-2 col-form-label">Kode Barang</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('kode_barang') is-invalid @enderror"
                                    name="kode_barang" id="kode_barang" autocomplete="off" value="{{ old('kode_barang') }}">
                                @error('kode_barang')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nama_barang" class="col-sm-2 col-form-label">Nama Barang</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('nama_barang') is-invalid @enderror"
                                    name="nama_barang" id="nama_barang" autocomplete="off" value="{{ old('nama_barang') }}">
                                @error('nama_barang')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="stok" class="col-sm-2 col-form-label">Stok</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('stok') is-invalid @enderror"
                                    name="stok" id="stok" autocomplete="off" value="{{ old('stok') }}">
                                @error('stok')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('harga') is-invalid @enderror"
                                    name="harga" id="harga" autocomplete="off" value="{{ old('harga') }}">
                                @error('harga')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/barang/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="container">
            <div class="card border-success">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                    Edit Data Barang
                    <a href="{{ route('barang.index') }}" class="btn btn-outline-success btn-sm">Kembali</a>
                </div>
                <div class="card-body ">
                    <form action="{{ route('barang.update', $result->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="mb-3 row">
                            <label for="kode_barang" class="col-sm-2 col-form-label">Kode Barang</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('kode_barang') is-invalid @enderror"
                                    name="kode_barang" id="kode_barang" autocomplete="off"
                                    value="{{ $result->kode_barang }}">
                                @error('kode_barang')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="nama_barang" class="col-sm-2 col-form-label">Nama Barang</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('nama_barang') is-invalid @enderror"
                                    name="nama_barang" id="nama_barang" autocomplete="off"
                                    value="{{ $result->nama_barang }}">
                                @error('nama_barang')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="stok" class="col-sm-2 col-form-label">Stok</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('stok') is-invalid @enderror"
                                    name="stok" id="stok" autocomplete="off" value="{{ $result->stok_barang }}">
                                @error('stok')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control @error('harga') is-invalid @enderror"
                                    name="harga" id="harga" autocomplete="off" value="{{ $result->harga_barang }}">
                                @error('harga')
                                    <div class="form-text text-danger">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div>
                            <button class="btn btn-warning btn-sm" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/barang/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="p-5">
        <div class="card border-success">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center border-success">
                Form Barang
                <a href="{{ route('barang.create') }}" class="btn btn-outline-primary btn-sm">Tambah Data</a>
            </div>
            <div class="card-body table-responsive">
                <table id="example" class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Kode Barang</th>
                            <th>Nama Barang</th>
                            <th>Stok</th>
                            <th>Harga</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($results as $res)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $res->kode_barang }}</td>
                                <td>{{ $res->nama_barang }}</td>
                                <td>{{ $res->stok_barang }}</td>
                                <td>{{ $res->harga_barang }}</td>
                                <td>
                                    <form onsubmit="return confirm('Apakah anda yakin?')"
                                        action="{{ route('barang.destroy', $res->id) }}" method="POST">
                                        <a href="{{ route('barang.edit', $res->id) }}"
                                            class="btn btn-outline-warning btn-sm btn-block">Edit</a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="btn btn-outline-danger btn-sm btn-block">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection